"""
Modelo acústico exploratório: concentração de moléculas prebióticas via
campo sonoro gerado por fumarolas hidrotermais (Fase 2 do projeto).

HIPÓTESE TESTADA (formulação do usuário): o campo acústico real gerado
por fumarolas hidrotermais pode transportar/concentrar moléculas
prebióticas em regiões de interferência das ondas que se propagam nesse
campo. Nenhuma publicação encontrada na pesquisa que fundamenta este
módulo propõe esse mecanismo para vents hidrotermais — é uma hipótese
original, não uma implementação de um modelo já publicado. Ver seção
"Limitações" em docs/PHYSICS_MODEL.md antes de citar qualquer resultado
deste módulo.

Fonte acústica real (não hipotética): Crone, T.J., Wilcock, W.S.D.,
Barclay, A.H., & Parsons, J.D. (2006). "The Sound Generated by
Mid-Ocean Ridge Black Smoker Hydrothermal Vents." PLOS ONE 1(1): e133.
Vents "Sully" e "Puffer" (Endeavour, Juan de Fuca) medidos: sinal de
banda larga 5-500 Hz (10-30 dB acima do ruído ambiente), tons estreitos
10-250 Hz (largura 5-15 Hz, 10-20 dB acima da banda larga), pressão RMS
0.4-2.6 Pa. Mecanismos propostos por Crone et al.: fluxo pulsante
(monopolo no orifício), mistura turbulenta (dipolo), interação
fluido-estrutura na chaminé, ressonância tipo Helmholtz/quarto-de-onda
na própria chaminé.

PROBLEMA FÍSICO CENTRAL identificado antes de implementar (ver
conversa que motivou este módulo): a força de radiação acústica clássica
(potencial de Gor'kov) escala com o volume da partícula (∝r³) e não tem
efeito demonstrado sobre moléculas livres dissolvidas (sub-nm a poucos
nm) — só é eficaz a partir de ~1 μm. "Moléculas presas diretamente em
nós de interferência" não é defensável com a acustofluídica conhecida.
Este módulo por isso implementa DOIS mecanismos fisicamente distintos e
deixa o usuário escolher (`mode`):

- "streaming": streaming acústico (fluxo secundário de contorno,
  Rayleigh/Nyborg) advecta e retém SOLUTO DISSOLVIDO de fato — o
  mecanismo correto para moléculas livres, independente de tamanho.
  Implementado resolvendo a equação de advecção-difusão estacionária
  real (não uma fórmula heurística) com e sem o campo de streaming, e
  comparando as duas soluções (mesmo padrão de controle usado em
  prebiotic.py).
- "particle_trap": armadilha de partícula via potencial de Gor'kov
  (colóide mineral de sulfeto, >1 μm, dentro do regime onde a força de
  radiação de fato funciona); a concentração MOLECULAR é assumida
  proporcional à concentração local de partícula (aproximação
  documentada — ver docs/PHYSICS_MODEL.md).
- "both": os dois mecanismos compostos multiplicativamente.

Interferência coerente vs. incoerente ENTRE vents diferentes
(`cross_vent_coherence`, ver `compute_acoustic_field`): não há evidência
de sincronismo de fase entre fumarolas independentes (Crone et al. só
reportam modulação de AMPLITUDE por maré, não travamento de fase), e as
linhas tonais têm banda finita (5-15 Hz) implicando tempo de coerência
curto (~dezenas de ms) — franjas de interferência ENTRE vents
diferentes não seriam estáveis no tempo. Por isso o modo padrão
("incoherent") modela apenas a auto-interferência de CADA fumarola com
sua própria imagem refletida no fundo local (fonte + espelho, mesma
fonte, geometria fixa = sempre coerente e estável, independente de
qualquer suposição de fase entre vents) — e soma os campos de
diferentes vents em POTÊNCIA (incoerente). Isso ainda produz uma
estrutura espacial real de nós/antinós (franjas), só que ancorada em
cada fumarola individualmente, não em batimentos entre fumarolas
distintas.

Essa é uma suposição por AUSÊNCIA de evidência (Crone et al. 2006 não
mede coerência de fase entre vents vizinhos), não uma medição que
descarta o cenário oposto. Um cenário fisicamente plausível de
coerência parcial existe: vents do mesmo cluster, com chaminés de
altura semelhante, poderiam ter frequências de ressonância tonal
próximas e ficar parcialmente travados em fase. Para testar se essa
suposição importa para a conclusão do modelo, `cross_vent_coherence`
também aceita "coherent": um cenário deliberadamente idealizado de
MELHOR CASO em que TODAS as fumarolas compartilham uma única frequência
tonal sorteada (em vez de uma por fumarola) e seus fasores de
pressão/velocidade são somados em fase, não em potência — um limite
superior otimista, não uma previsão realista, usado para delimitar
(bounding test) o quanto a suposição de incoerência afeta o resultado:
se mesmo esse limite otimista continuar fisicamente irrelevante (poço
de Gor'kov << kT), a conclusão de irrelevância do mecanismo fica mais
robusta; se o limite otimista cruzar o limiar, isso é um achado
específico e testável (preveria estrutura acústica de fundo diferente
entre clusters de altura de chaminé homogênea vs. heterogênea). O ruído
de banda larga (turbulência) nunca é somado coerentemente em nenhum dos
dois modos — coerência é um conceito de linha tonal, não de ruído de
banda larga.

CORREÇÃO (2026-08-06): antes desta versão, o termo de VELOCIDADE
(usado tanto pelo streaming de contorno quanto pelo potencial de
Gor'kov) somava os fasores complexos de velocidade de fumarolas
DIFERENTES antes de elevar ao quadrado — uma soma coerente de fato,
inconsistente com a soma em potência já usada (corretamente) para a
PRESSÃO, e sem sentido físico bem definido quando as fumarolas somadas
têm frequências tonais diferentes (fasores de frequências diferentes
não podem ser somados como um único fasor). Isso vazava uma forma de
interferência coerente ENTRE vents não documentada e não pretendida,
por um caminho diferente do da pressão. Corrigido: o termo de
velocidade agora segue exatamente a mesma escolha de
`cross_vent_coherence` que o termo de pressão (soma em potência por
padrão; soma em fase só no modo "coherent" explícito, com frequência
compartilhada).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple, TYPE_CHECKING

import numpy as np
from scipy import sparse
from scipy.sparse.linalg import spsolve
from scipy.ndimage import maximum_filter

import plume_physics as pp

if TYPE_CHECKING:
    from fumarola_field import Vent

# --------------------------------------------------------------------------
# Constantes físicas e defaults citados (ver docs/PHYSICS_MODEL.md)
# --------------------------------------------------------------------------

RHO_SEAWATER = pp.RHO_SEAWATER          # kg/m^3, mesma constante de plume_physics.py
K_BOLTZMANN = 1.380649e-23              # J/K (exato, SI 2019)
AMBIENT_TEMP_C_DEFAULT = pp.AMBIENT_TEMP_C

# --- fonte: Crone et al. (2006) ---
BROADBAND_RMS_PA_RANGE = (0.4, 2.6)      # Pa, banda 5-500 Hz, medido
TONAL_FREQ_RANGE_HZ = (10.0, 250.0)      # tons estreitos, medido
TONAL_BANDWIDTH_HZ = (5.0, 15.0)         # largura das linhas tonais, medido
TONAL_EXCESS_DB_RANGE = (10.0, 20.0)     # tom acima da banda larga, medido
# Distância de referência da fonte: a distância exata hidrofone-orifício
# em Crone et al. (2006) não foi verificada no material consultado (não
# acessamos o texto completo/métodos). Tratamos os valores de pressão
# RMS medidos como representativos a uma distância de referência nominal
# de 1 m — aproximação explícita, não um dado medido diretamente.
REFERENCE_DISTANCE_M = 1.0
# Coeficiente de reflexão do fundo: basalto/sulfeto maciço têm impedância
# acústica muito maior que água do mar, favorecendo reflexão quase total
# em fase (fundo "rígido", ver p.ex. Jensen, Kuperman, Porter & Schmidt,
# "Computational Ocean Acoustics"). Usamos 0.9 (alta, mas não perfeita)
# como valor plausível não medido para o fundo mineralizado específico
# de um campo de vents — não uma medição citada.
BOTTOM_REFLECTION_COEFF = 0.9

# --- população de partículas para o modo "particle_trap" ---
# Duas classes de tamanho ANCORADAS EM LITERATURA (não uma distribuição
# contínua ajustada — os dados disponíveis só sustentam dois pontos de
# ancoragem, ver docs/PHYSICS_MODEL.md):
#
# 1. Colóide fino de sulfeto recém-nucleado: Klevenz et al. (2011),
#    Geochem. Geophys. Geosyst. 12, Q0AE05 — CORREÇÃO (2026-08-08,
#    verificado por leitura direta do PDF primário completo): o artigo
#    NÃO reporta tamanho/diâmetro de partícula em lugar nenhum (é um
#    estudo de composição geoquímica/mineralógica — chalcopirita,
#    esfalerita, pirita etc. — não de granulometria). "0.2 μm" é o poro
#    do filtro de policarbonato usado na AMOSTRAGEM (seção 2.2 do
#    artigo: "filtered through 0.2 μM polycarbonate membrane filters"),
#    não uma medição de que "partículas de Cu/Zn formam >0.2 μm" — a
#    formulação anterior deste comentário confundia metodologia de
#    coleta com resultado medido. O que É legitimamente citável: as
#    partículas coletadas são, por construção do filtro, ≥0.2 μm
#    nominalmente; usamos 2 μm (uma ordem de grandeza acima desse piso)
#    como valor plausível não medido para o regime fino, densidade de
#    pirita (FeS2, manual de mineralogia, não do artigo).
# 2. Agregado de oxi-hidróxido de Fe de campo próximo: González-Santana,
#    D., Planquette, H., Cheize, M., Whitby, H., Gourain, A., Holmes,
#    T., et al. (2020), "Processes driving iron and manganese dispersal
#    from the TAG hydrothermal plume (Mid-Atlantic Ridge)," Front. Mar.
#    Sci. 7:568 — raios de agregado 14-20 μm no primeiro km da pluma do
#    TAG (derivados de velocidade de sedimentação via lei de Stokes),
#    densidade 2400-3600 kg/m³ (goethita/oxi-hidróxido de Fe amorfo).
#    Usamos os PONTOS MÉDIOS dessas faixas (17 μm, 3000 kg/m³). Valores
#    (14-20 μm, 2400-3600 kg/m³, velocidade de sedimentação 45±6 m/dia
#    no 1º km) verificados por leitura direta do PDF primário completo
#    em 2026-08-06 (biblios/fmars.2020.00568.pdf) — sem divergência do
#    que já estava documentado aqui.
#
# É o maior tamanho de agregado hidrotermal com raio bem documentado na
# pesquisa de literatura que fundamenta este modelo — ainda assim ~5-6x
# menor que o raio necessário para a armadilha de Gor'kov cruzar k_BT
# nas pressões acústicas reais medidas (ver
# test_gorkov_trap_remains_negligible_for_largest_documented_aggregate em
# tests/test_acoustics.py) — um achado quantitativo, não uma suposição.
PARTICLE_CLASSES = {
    "fine_sulfide_colloid": {
        "radius_m": 2.0e-6,
        "density_kg_m3": 5010.0,
        "label": "colóide fino de sulfeto (pirita, ordem de grandeza; Klevenz et al. 2011)",
    },
    "near_field_fe_oxyhydroxide_aggregate": {
        "radius_m": 17.0e-6,
        "density_kg_m3": 3000.0,
        "label": "agregado de oxi-hidróxido de Fe, campo próximo (González-Santana et al. 2020, pluma TAG)",
    },
}
PRIMARY_PARTICLE_CLASS = "near_field_fe_oxyhydroxide_aggregate"  # maior/mais favorável das duas

# Módulos elásticos de colóides/agregados de Fe/S em escala micro/nano
# não estão bem determinados na literatura consultada para nenhuma das
# duas classes; tratamos a partícula no LIMITE RÍGIDO (incompressível
# frente à água, f1≈1) em vez de assumir um módulo de compressibilidade
# específico não verificado.

# --- soluto dissolvido para o modo "streaming" ---
# Difusividade molecular de solutos orgânicos pequenos e polares em água,
# ordem de grandeza de manual (Cussler, E.L., "Diffusion: Mass Transfer
# in Fluid Systems") — não um valor medido para aminoácidos a 2°C
# especificamente.
DEFAULT_SOLUTE_DIFFUSIVITY_M2_S = 8.0e-10


# --------------------------------------------------------------------------
# 1. Propriedades acústicas da água do mar
# --------------------------------------------------------------------------

def sound_speed_seawater(temp_c: float, depth_m: float, salinity_psu: float = 34.7) -> float:
    """
    Velocidade do som na água do mar — equação de nove termos de
    Mackenzie, K.V. (1981), "Nine-term equation for sound speed in the
    oceans," J. Acoust. Soc. Am. 70(3), 807-812 (verificado por leitura
    direta do PDF primário completo, 2026-08-08: os 9 coeficientes batem
    exatamente com a eq. (1) do artigo). Válida para T=-2 a 30°C, S=25-40
    psu, D=0-8000 m — cobre com folga as condições ambientes deste
    projeto (T=2°C, D~2000-3000m).
    """
    t, s, d = temp_c, salinity_psu, depth_m
    return (
        1448.96 + 4.591 * t - 5.304e-2 * t**2 + 2.374e-4 * t**3
        + 1.340 * (s - 35) + 1.630e-2 * d + 1.675e-7 * d**2
        - 1.025e-2 * t * (s - 35) - 7.139e-13 * t * d**3
    )


def seawater_absorption_np_per_m(freq_hz: float, temp_c: float, depth_m: float,
                                  salinity_psu: float = 34.7, ph: float = 7.8) -> float:
    """
    Coeficiente de absorção acústica da água do mar, convertido para
    Np/m. Fórmula simplificada de Ainslie, M.A., & McColm, J.G. (1998),
    "A simplified formula for viscous and chemical absorption in sea
    water," J. Acoust. Soc. Am. 103(3), 1671-1672 (relaxação de ácido
    bórico + MgSO4 + viscosidade da água pura).

    Nas frequências de interesse aqui (10-500 Hz, banda medida por Crone
    et al. 2006), o resultado é da ordem de 1e-3 dB/km — desprezível ao
    longo da escala do domínio simulado (centenas a ~1 km): por isso o
    termo é calculado e aplicado (não simplesmente omitido), mas o efeito
    numérico é, de fato, mínimo. Ver tests/test_acoustics.py para o
    valor de referência.
    """
    f_khz = freq_hz / 1000.0
    d_km = depth_m / 1000.0
    t, s = temp_c, salinity_psu

    f1 = 0.78 * math.sqrt(s / 35.0) * math.exp(t / 26.0)
    f2 = 42.0 * math.exp(t / 17.0)

    term_boric = 0.106 * (f1 * f_khz**2) / (f1**2 + f_khz**2) * math.exp((ph - 8.0) / 0.56)
    term_mgso4 = (0.52 * (1 + t / 43.0) * (s / 35.0) * (f2 * f_khz**2) / (f2**2 + f_khz**2)
                  * math.exp(-d_km / 6.0))
    term_water = 0.00049 * f_khz**2 * math.exp(-(t / 27.0 + d_km / 17.0))

    alpha_db_per_km = term_boric + term_mgso4 + term_water
    return alpha_db_per_km / 8.686 / 1000.0  # dB/km -> Np/m


# --------------------------------------------------------------------------
# 2. Modelo de fonte por fumarola (Crone et al., 2006)
# --------------------------------------------------------------------------

@dataclass
class VentAcousticSource:
    vent_id: int
    x_m: float
    y_m: float
    floor_elev_m: float        # elevação local do fundo (relativa), usada como plano-espelho
    source_height_m: float     # altura do orifício acima do fundo local (~altura da chaminé)
    freq_hz: float              # frequência do tom estreito, amostrada empiricamente
    p_ref_broadband_pa: float   # pressão RMS de banda larga na distância de referência
    p_ref_tonal_pa: float       # pressão RMS do tom estreito na distância de referência


def build_acoustic_sources(vents: List["Vent"], terrain: np.ndarray, domain_size_m: float,
                            local_relief_m: float, rng: np.random.Generator,
                            cross_vent_coherence: str = "incoherent") -> List[VentAcousticSource]:
    """
    Constrói uma fonte acústica por fumarola. A frequência do tom NÃO é
    derivada da geometria da chaminé por uma fórmula mecanicista: Crone
    et al. (2006) propõem ressonância tipo Helmholtz/quarto-de-onda como
    UMA hipótese entre várias mecanismos possíveis, sem fornecer uma
    relação geometria->frequência fechada e verificada. Por isso a
    frequência é amostrada da faixa empiricamente observada (10-250 Hz),
    não calculada a partir de `chimney_height_m` — uma escolha
    deliberadamente mais honesta que fingir uma relação não estabelecida
    na fonte primária.

    `cross_vent_coherence="coherent"`: pré-condição física necessária
    para que fumarolas diferentes possam ter franjas de interferência
    estáveis entre si (ver docstring do módulo) — todas as fumarolas
    recebem a MESMA frequência tonal (sorteada uma única vez), em vez de
    uma frequência independente por fumarola. Cenário de melhor caso
    idealizado, não uma medição.
    """
    size = terrain.shape[0]
    meters_per_cell = domain_size_m / (size - 1)
    shared_freq_hz = float(rng.uniform(*TONAL_FREQ_RANGE_HZ)) if cross_vent_coherence == "coherent" else None
    sources = []
    for v in vents:
        xi, yi = int(np.clip(v.x, 0, size - 1)), int(np.clip(v.y, 0, size - 1))
        floor_elev_m = float(terrain[yi, xi] * local_relief_m)
        freq_hz = shared_freq_hz if shared_freq_hz is not None else float(rng.uniform(*TONAL_FREQ_RANGE_HZ))
        broadband_pa = float(rng.uniform(*BROADBAND_RMS_PA_RANGE))
        excess_db = float(rng.uniform(*TONAL_EXCESS_DB_RANGE))
        tonal_pa = broadband_pa * 10 ** (excess_db / 20.0)
        sources.append(VentAcousticSource(
            vent_id=v.id, x_m=v.x * meters_per_cell, y_m=v.y * meters_per_cell,
            floor_elev_m=floor_elev_m, source_height_m=max(v.chimney_height_m, 0.5),
            freq_hz=freq_hz, p_ref_broadband_pa=broadband_pa, p_ref_tonal_pa=tonal_pa,
        ))
    return sources


# --------------------------------------------------------------------------
# 3. Campo de pressão: auto-interferência fonte + imagem no fundo
# --------------------------------------------------------------------------

def _source_image_distances(source: VentAcousticSource, X: np.ndarray, Y: np.ndarray,
                             z_receiver: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
    z_direct = source.floor_elev_m + source.source_height_m
    z_image = source.floor_elev_m - source.source_height_m
    r_direct = np.sqrt((X - source.x_m) ** 2 + (Y - source.y_m) ** 2 + (z_receiver - z_direct) ** 2)
    r_image = np.sqrt((X - source.x_m) ** 2 + (Y - source.y_m) ** 2 + (z_receiver - z_image) ** 2)
    floor = REFERENCE_DISTANCE_M * 0.5
    return np.maximum(r_direct, floor), np.maximum(r_image, floor)


def vent_tonal_pressure_phasor(source: VentAcousticSource, X: np.ndarray, Y: np.ndarray,
                                z_receiver: np.ndarray, c_sound: float,
                                alpha_np_per_m: float) -> np.ndarray:
    """
    Fasor complexo de pressão do tom estreito desta fumarola: soma
    COERENTE direto + imagem (mesma fonte, geometria fixa -> sempre
    válida, sem suposição de fase entre fumarolas). |resultado|^2 é a
    intensidade da onda estacionária de auto-interferência dessa
    fumarola sozinha — o efeito clássico do "espelho de Lloyd" (Lloyd's
    mirror; ver Urick, R.J., "Principles of Underwater Sound") aplicado
    a uma fumarola perto do fundo.

    Limitação de visibilidade de franjas, importante e não-óbvia: a
    diferença máxima de caminho fonte-vs-imagem é limitada a
    2×(altura do receptor) = 2×1m = 2m (receptor fixo a 1m do fundo,
    ver `receiver_height_m`), INDEPENDENTE da altura da chaminé. Nas
    frequências reais medidas por Crone et al. (2006) (10-250 Hz,
    λ=6-150m), essa diferença de caminho cobre MENOS de um ciclo
    completo de interferência (4×1m/λ < 1 para λ>4m) — ou seja, a
    auto-interferência de campo próximo real, nas condições deste
    modelo, aparece como um único realce/sombra suave perto da
    fumarola, não como múltiplos nós/antinós periódicos. Franjas
    múltiplas só aparecem para frequências bem mais altas que a faixa
    medida (ver tests/test_acoustics.py, onde 1000 Hz é usado
    deliberadamente para validar a matemática, não para representar a
    faixa real).
    """
    r_direct, r_image = _source_image_distances(source, X, Y, z_receiver)
    k = 2 * np.pi * source.freq_hz / c_sound
    amp_direct = source.p_ref_tonal_pa * REFERENCE_DISTANCE_M / r_direct * np.exp(-alpha_np_per_m * r_direct)
    amp_image = source.p_ref_tonal_pa * REFERENCE_DISTANCE_M / r_image * np.exp(-alpha_np_per_m * r_image)
    return amp_direct * np.exp(1j * k * r_direct) + BOTTOM_REFLECTION_COEFF * amp_image * np.exp(1j * k * r_image)


def vent_broadband_pressure_rms(source: VentAcousticSource, X: np.ndarray, Y: np.ndarray,
                                 z_receiver: np.ndarray, alpha_np_per_m: float) -> np.ndarray:
    """
    Componente de banda larga: turbulência de fluxo, sem relação de fase
    fixa através da banda (5-500 Hz) -> a interferência fina entre
    direto/imagem se borra ao integrar sobre a banda. Soma-se em
    potência (incoerente), não em fase.
    """
    r_direct, r_image = _source_image_distances(source, X, Y, z_receiver)
    amp_direct = source.p_ref_broadband_pa * REFERENCE_DISTANCE_M / r_direct * np.exp(-alpha_np_per_m * r_direct)
    amp_image = source.p_ref_broadband_pa * REFERENCE_DISTANCE_M / r_image * np.exp(-alpha_np_per_m * r_image)
    return np.sqrt(amp_direct ** 2 + (BOTTOM_REFLECTION_COEFF * amp_image) ** 2)


def _particle_velocity_from_pressure(p_phasor: np.ndarray, meters_per_cell: float,
                                      omega: float, rho: float) -> Tuple[np.ndarray, np.ndarray]:
    """
    Velocidade de partícula acústica (componentes horizontais) a partir
    da equação de momento linearizada: -iωρv = -∇p => v = ∇p/(iωρ).
    Relação GERAL (campo próximo ou distante), preferida aqui sobre o
    atalho de campo distante v≈p/(ρc) porque este último apagaria
    exatamente a separação nó-de-pressão/antinó-de-velocidade da onda
    estacionária de auto-interferência — que é o efeito físico central
    de que depende o mecanismo de aprisionamento (módulo Gor'kov,
    seção 5). Só as componentes horizontais são resolvidas (campo
    avaliado num plano horizontal fixo, ver seção 4) — a componente
    vertical não é modelada, limitação documentada.
    """
    dpdy, dpdx = np.gradient(p_phasor, meters_per_cell, meters_per_cell)
    denom = 1j * omega * rho
    return dpdx / denom, dpdy / denom


# --------------------------------------------------------------------------
# 4. Campo combinado (todas as fumarolas) + diagnósticos por fumarola
# --------------------------------------------------------------------------

@dataclass
class AcousticFieldResult:
    X: np.ndarray
    Y: np.ndarray
    meters_per_cell: float
    p2_tonal_total: np.ndarray
    p2_broadband_total: np.ndarray
    v2_tonal_total: np.ndarray       # |v|^2 tonal já combinado entre fumarolas (real)
    streaming_ux_total: np.ndarray   # velocidade de streaming DC já retificada e combinada (real)
    streaming_uy_total: np.ndarray
    sound_speed_m_s: float
    absorption_np_per_m_at_100hz: float
    per_vent_omega: Dict[int, float]
    cross_vent_coherence: str        # "incoherent" | "coherent" — modo usado para gerar este campo


def compute_acoustic_field(vents: List["Vent"], terrain: np.ndarray, domain_size_m: float,
                            local_relief_m: float, ocean_depth_baseline_m: float,
                            ambient_temp_c: float, salinity_psu: float, ph: float,
                            rng: np.random.Generator, receiver_height_m: float = 1.0,
                            cross_vent_coherence: str = "incoherent") -> AcousticFieldResult:
    """
    Soma, para todas as fumarolas, o campo de auto-interferência
    (direto+imagem) tonal e de banda larga.

    `cross_vent_coherence` controla como os campos de fumarolas
    DIFERENTES são combinados (ver docstring do módulo):
    - "incoherent" (padrão, fisicamente motivado): soma em POTÊNCIA
      (|p_i|², |v_i|²) — nenhuma fumarola é somada em fase com outra.
      A velocidade de streaming (mecanismo A) é retificada usando a
      frequência PRÓPRIA de cada fumarola e só então somada
      vetorialmente entre fumarolas (soma de escoamentos DC reais,
      sempre uma superposição válida, independente de coerência).
    - "coherent": cenário idealizado de melhor caso (todas as fumarolas
      compartilham uma única frequência sorteada, ver
      `build_acoustic_sources`) — os fasores de pressão e velocidade são
      somados em fase ANTES de elevar ao quadrado, produzindo franjas de
      interferência genuínas entre fumarolas distintas. Usado como
      limite superior (bounding test), não como previsão.

    O ruído de banda larga nunca é somado coerentemente (não é um
    conceito aplicável a ruído turbulento de banda larga).
    """
    if cross_vent_coherence not in ("incoherent", "coherent"):
        raise ValueError(f"cross_vent_coherence inválido: {cross_vent_coherence!r}")

    size = terrain.shape[0]
    meters_per_cell = domain_size_m / (size - 1)
    xs = np.arange(size) * meters_per_cell
    X, Y = np.meshgrid(xs, xs)
    elev_m = terrain * local_relief_m
    z_receiver = elev_m + receiver_height_m

    c_sound = sound_speed_seawater(ambient_temp_c, ocean_depth_baseline_m, salinity_psu)
    sources = build_acoustic_sources(vents, terrain, domain_size_m, local_relief_m, rng, cross_vent_coherence)

    p2_tonal_total = np.zeros_like(X)
    p2_broadband_total = np.zeros_like(X)
    v2_tonal_total = np.zeros_like(X)
    streaming_ux_total = np.zeros_like(X)
    streaming_uy_total = np.zeros_like(X)
    per_vent_omega: Dict[int, float] = {}

    # Acumuladores de fasor complexo, só usados no modo "coherent" (soma
    # em fase válida porque todas as fontes compartilham a mesma frequência).
    p_phasor_sum = np.zeros_like(X, dtype=complex)
    vx_phasor_sum = np.zeros_like(X, dtype=complex)
    vy_phasor_sum = np.zeros_like(X, dtype=complex)

    for src in sources:
        alpha = seawater_absorption_np_per_m(src.freq_hz, ambient_temp_c, ocean_depth_baseline_m, salinity_psu, ph)
        p_tonal = vent_tonal_pressure_phasor(src, X, Y, z_receiver, c_sound, alpha)

        alpha_bb = seawater_absorption_np_per_m(250.0, ambient_temp_c, ocean_depth_baseline_m, salinity_psu, ph)
        p_bb = vent_broadband_pressure_rms(src, X, Y, z_receiver, alpha_bb)
        p2_broadband_total += p_bb ** 2

        omega = 2 * np.pi * src.freq_hz
        vx_i, vy_i = _particle_velocity_from_pressure(p_tonal, meters_per_cell, omega, RHO_SEAWATER)
        per_vent_omega[src.vent_id] = omega

        if cross_vent_coherence == "coherent":
            p_phasor_sum += p_tonal
            vx_phasor_sum += vx_i
            vy_phasor_sum += vy_i
        else:
            p2_tonal_total += np.abs(p_tonal) ** 2
            v2_i = np.abs(vx_i) ** 2 + np.abs(vy_i) ** 2
            v2_tonal_total += v2_i
            # Streaming DC: retifica com a frequência PRÓPRIA desta fumarola,
            # depois soma vetorialmente (superposição de escoamentos DC reais
            # — válida independente de qualquer suposição de coerência).
            dv2_dy, dv2_dx = np.gradient(v2_i, meters_per_cell, meters_per_cell)
            coeff = -0.75 / omega
            streaming_ux_total += coeff * dv2_dx
            streaming_uy_total += coeff * dv2_dy

    if cross_vent_coherence == "coherent":
        p2_tonal_total = np.abs(p_phasor_sum) ** 2
        v2_tonal_total = np.abs(vx_phasor_sum) ** 2 + np.abs(vy_phasor_sum) ** 2
        # Frequência única compartilhada por construção (ver build_acoustic_sources).
        omega_shared = next(iter(per_vent_omega.values())) if per_vent_omega else 1.0
        dv2_dy, dv2_dx = np.gradient(v2_tonal_total, meters_per_cell, meters_per_cell)
        coeff = -0.75 / omega_shared
        streaming_ux_total = coeff * dv2_dx
        streaming_uy_total = coeff * dv2_dy

    alpha_ref = seawater_absorption_np_per_m(100.0, ambient_temp_c, ocean_depth_baseline_m, salinity_psu, ph)
    return AcousticFieldResult(
        X=X, Y=Y, meters_per_cell=meters_per_cell,
        p2_tonal_total=p2_tonal_total, p2_broadband_total=p2_broadband_total,
        v2_tonal_total=v2_tonal_total,
        streaming_ux_total=streaming_ux_total, streaming_uy_total=streaming_uy_total,
        sound_speed_m_s=c_sound, absorption_np_per_m_at_100hz=alpha_ref,
        per_vent_omega=per_vent_omega, cross_vent_coherence=cross_vent_coherence,
    )


# --------------------------------------------------------------------------
# 5. Mecanismo B: potencial de Gor'kov + distribuição de Boltzmann
# --------------------------------------------------------------------------

def gorkov_contrast_factors(particle_density_kg_m3: float, fluid_density_kg_m3: float = RHO_SEAWATER
                             ) -> Tuple[float, float]:
    """
    Fatores de contraste monopolar/dipolar do potencial de Gor'kov
    (Gor'kov, L.P., 1962, Sov. Phys. Dokl. 6, 773-775; formulação
    moderna em Bruus, H., 2012, "Acoustofluidics 7," Lab Chip 12,
    1014-1021): f1=1-1/(Λσ²), f2=2(Λ-1)/(2Λ+1), Λ=ρ_p/ρ_f, σ=c_p/c_f.

    Partícula tratada no LIMITE RÍGIDO (κ_p→0, ou seja σ→∞, f1→1) —
    módulos elásticos de colóides de sulfeto autigênico em escala
    nanométrica não estão bem determinados na literatura consultada;
    assumir um valor específico de compressibilidade seria uma precisão
    falsa. f2 é calculado normalmente a partir da razão de densidades
    real (bem definida para pirita/mackinawita).
    """
    f1 = 1.0  # limite rígido
    lam = particle_density_kg_m3 / fluid_density_kg_m3
    f2 = 2.0 * (lam - 1.0) / (2.0 * lam + 1.0)
    return f1, f2


def gorkov_potential_field(field: AcousticFieldResult, particle_radius_m: float,
                            particle_density_kg_m3: float) -> np.ndarray:
    """
    Potencial de Gor'kov total (soma sobre fumarolas, cada uma
    contribuindo seu próprio ⟨p²⟩,⟨v²⟩ de auto-interferência — a soma é
    válida porque U é linear em ⟨p²⟩ e ⟨v²⟩ separadamente, mesmo que a
    combinação ENTRE fumarolas seja incoerente em intensidade):

    U = V0 * [ f1*⟨p²⟩/(2ρc²) - (3/4)*f2*ρ*⟨v²⟩ ]

    Mínimos de U são pontos de equilíbrio estável (armadilha). Para
    partícula densa/rígida (f1>0, f2>0, caso de sulfeto em água — ver
    teste de sinal em tests/test_acoustics.py) a armadilha ocorre em
    nós de pressão / antinós de velocidade, resultado padrão da
    acustofluídica (consistente com o comportamento de partículas
    densas observado na literatura).
    """
    f1, f2 = gorkov_contrast_factors(particle_density_kg_m3)
    v0 = (4.0 / 3.0) * np.pi * particle_radius_m ** 3
    c = field.sound_speed_m_s
    rho = RHO_SEAWATER

    mean_p2 = field.p2_tonal_total
    mean_v2 = field.v2_tonal_total

    return v0 * (f1 * mean_p2 / (2 * rho * c ** 2) - 0.75 * f2 * rho * mean_v2)


def particle_boltzmann_enhancement(u_field: np.ndarray, temp_c: float) -> Tuple[np.ndarray, float]:
    """
    Distribuição de equilíbrio de partículas num potencial estático
    U(x,y): n(x,y) ∝ exp(-U(x,y)/(k_B T)) — resultado direto de mecânica
    estatística de equilíbrio (distribuição de Boltzmann), não uma
    fórmula heurística ajustada. Normalizado para que o ponto de MENOR
    concentração do domínio valha 1x (fator de enriquecimento ≥ 1 em
    todo o campo, por construção).

    Retorna também `max_depth_over_kT` = (U_max-U_min)/(k_B T): a
    profundidade do poço de potencial em unidades de energia térmica.
    Se << 1, a "armadilha" é fisicamente irrelevante (agitação térmica
    domina completamente) — um diagnóstico honesto sobre se o mecanismo
    é sequer plausível nas pressões acústicas reais medidas por Crone et
    al. (2006), que são muito baixas comparadas a dispositivos de
    acustoforese de laboratório (kPa-MPa vs. ~1-3 Pa aqui).
    """
    temp_k = temp_c + 273.15
    kt = K_BOLTZMANN * temp_k
    u_max = float(np.max(u_field))
    u_min = float(np.min(u_field))
    depth_over_kt = (u_max - u_min) / kt if kt > 0 else 0.0
    enhancement = np.exp(-(u_field - u_max) / kt) if kt > 0 else np.ones_like(u_field)
    return enhancement, depth_over_kt


# --------------------------------------------------------------------------
# 6. Mecanismo A: streaming de contorno (Rayleigh/Nyborg) + advecção-difusão
# --------------------------------------------------------------------------

def boundary_streaming_velocity(field: AcousticFieldResult) -> Tuple[np.ndarray, np.ndarray]:
    """
    Velocidade de streaming de contorno (limite externo da camada
    limite viscosa), lei de Rayleigh/Nyborg:
    U_slip = -(3/(4ω)) * d⟨U0²⟩/dx  (Rayleigh, Lord, 1884, Phil. Trans.
    R. Soc. 175, 1-21; forma explícita usada aqui de Nyborg, W.L., 1958,
    "Acoustic streaming near a boundary," J. Acoust. Soc. Am. 30(4),
    329-339, eq. 28c: `u_L = -(3/(8ω))*d(u_a0²)/dx`).

    Verificado por leitura direta do PDF primário completo (2026-08-08):
    a eq. (28c) do artigo usa AMPLITUDE DE PICO `u_a0` no denominador
    (fator 1/8, não 1/4) — a diferença de fator 2 aparente em relação a
    `coeff = -0.75/omega` no código é reconciliada porque `v2_i`/
    `v2_tonal_total` aqui são construídos a partir de `p_ref_tonal_pa`
    (RMS, ver `VentAcousticSource`), logo `⟨U0²⟩ = u_a0²/2` — substituindo,
    `-(3/(4ω))*d(u_a0²/2)/dx = -(3/(8ω))*d(u_a0²)/dx`, idêntico à eq.
    (28c). As duas formas são o mesmo resultado em convenções de
    amplitude diferentes (pico vs. RMS), não uma divergência real.

    Extensão de engenharia documentada: a fórmula classica é 1D, ao
    longo de um contorno. Aqui é aplicada como o gradiente 2D completo
    do campo de velocidade-amplitude-ao-quadrado (não uma transcrição
    literal da fórmula 1D) — uma generalização razoável, não uma
    citação direta.

    Já retificada e combinada entre fumarolas em `compute_acoustic_field`
    (no modo "incoherent", cada fumarola é retificada com sua própria
    frequência e só então somada vetorialmente entre fumarolas — soma de
    escoamentos DC reais, sempre válida; no modo "coherent", retificada
    uma única vez a partir do campo de velocidade já somado em fase — ver
    `cross_vent_coherence`). Esta função apenas expõe o resultado já
    calculado, mantida como função separada por compatibilidade com o
    restante do módulo/testes.

    O streaming de Eckart (bulk, por absorção) NÃO é usado como
    mecanismo principal aqui: nas frequências de Crone et al. (10-500
    Hz) a absorção da água do mar é ordem 1e-3 dB/km (ver
    `seawater_absorption_np_per_m`), tornando a força de streaming de
    bulk (∝ absorção × intensidade, Eckart, C., 1948, Phys. Rev. 73(1),
    68-76) desprezível nessa escala — o streaming de contorno domina.
    """
    return field.streaming_ux_total, field.streaming_uy_total


def solve_steady_advection_diffusion(u_x: np.ndarray, u_y: np.ndarray, source_mask: np.ndarray,
                                      meters_per_cell: float, diffusivity_m2_s: float,
                                      loss_rate_per_s: float) -> np.ndarray:
    """
    Resolve D*grad^2(C) - u.grad(C) - k*C + S = 0 em regime estacionário
    por diferenças finitas (advecção upwind de 1ª ordem — necessária
    para estabilidade numérica: o número de Péclet de malha aqui é
    tipicamente >>1, então diferenças centrais para advecção seriam
    numericamente instáveis; upwind é a escolha padrão, incondicional-
    mente estável, para esse regime), montando um sistema linear esparso
    e resolvendo via `scipy.sparse.linalg.spsolve`. Contorno de
    Dirichlet C=0 nas bordas do domínio (solvente livre no oceano
    aberto, longe de qualquer fumarola).

    `loss_rate_per_s` (perda genérica, não uma taxa química medida) é
    necessária para que o problema seja bem-posto: difusão 2D
    estacionária pura, sem nenhum termo de perda, não tem solução
    localizada finita para uma fonte puntual num domínio infinito — é
    uma escolha de condicionamento numérico, documentada como tal, não
    uma cinética de decaimento calibrada.
    """
    ny, nx = source_mask.shape
    h = meters_per_cell
    n = ny * nx

    def idx(i, j):
        return i * nx + j

    rows, cols, vals = [], [], []
    rhs = np.zeros(n)

    for i in range(ny):
        for j in range(nx):
            k = idx(i, j)
            if i == 0 or i == ny - 1 or j == 0 or j == nx - 1:
                rows.append(k); cols.append(k); vals.append(1.0)
                rhs[k] = 0.0
                continue

            diag = -4.0 * diffusivity_m2_s / h**2 - loss_rate_per_s
            rows.append(k); cols.append(k); vals.append(diag)

            for di, dj in ((-1, 0), (1, 0), (0, -1), (0, 1)):
                rows.append(k); cols.append(idx(i + di, j + dj)); vals.append(diffusivity_m2_s / h**2)

            ux, uy = u_x[i, j], u_y[i, j]
            # advecção upwind de 1ª ordem em x
            if ux >= 0:
                rows.append(k); cols.append(idx(i, j)); vals.append(-ux / h)
                rows.append(k); cols.append(idx(i, j - 1)); vals.append(ux / h)
            else:
                rows.append(k); cols.append(idx(i, j)); vals.append(ux / h)
                rows.append(k); cols.append(idx(i, j + 1)); vals.append(-ux / h)
            # advecção upwind de 1ª ordem em y
            if uy >= 0:
                rows.append(k); cols.append(idx(i, j)); vals.append(-uy / h)
                rows.append(k); cols.append(idx(i - 1, j)); vals.append(uy / h)
            else:
                rows.append(k); cols.append(idx(i, j)); vals.append(uy / h)
                rows.append(k); cols.append(idx(i + 1, j)); vals.append(-uy / h)

            rhs[k] = -source_mask[i, j]

    A = sparse.csr_matrix((vals, (rows, cols)), shape=(n, n))
    c_flat = spsolve(A, rhs)
    return c_flat.reshape(ny, nx)


def _vent_source_mask(vents: List["Vent"], grid_size: int, sigma_cells: float = 1.5) -> np.ndarray:
    """Máscara de síntese: pico gaussiano em cada fumarola, representando produção local contínua."""
    mask = np.zeros((grid_size, grid_size))
    yy, xx = np.mgrid[0:grid_size, 0:grid_size]
    for v in vents:
        mask += np.exp(-((xx - v.x) ** 2 + (yy - v.y) ** 2) / (2 * sigma_cells ** 2))
    return mask


def streaming_enrichment_field(field: AcousticFieldResult, vents: List["Vent"], domain_size_m: float,
                                diffusivity_m2_s: float = DEFAULT_SOLUTE_DIFFUSIVITY_M2_S
                                ) -> Tuple[np.ndarray, float]:
    """
    Compara a concentração estacionária de soluto COM streaming de
    contorno vs. SEM (controle, u=0), mesma fonte e mesma perda —
    mesmo padrão de comparação-contra-controle usado em prebiotic.py.
    Retorna (campo de enriquecimento, velocidade de streaming máxima em m/s).
    """
    ux, uy = boundary_streaming_velocity(field)
    grid_size = field.X.shape[0]
    source_mask = _vent_source_mask(vents, grid_size)
    loss_rate = diffusivity_m2_s / (domain_size_m / 4.0) ** 2

    c_stream = solve_steady_advection_diffusion(ux, uy, source_mask, field.meters_per_cell,
                                                 diffusivity_m2_s, loss_rate)
    c_control = solve_steady_advection_diffusion(np.zeros_like(ux), np.zeros_like(uy), source_mask,
                                                  field.meters_per_cell, diffusivity_m2_s, loss_rate)

    # Razão regularizada por um piso comum (não só no denominador): perto
    # das bordas do domínio (Dirichlet C=0), COM e SEM streaming decaem
    # para o mesmo piso numérico, então a razão bruta fica dominada por
    # ruído de ponto flutuante e pode cair para exatamente 0 — um
    # artefato numérico, não um efeito físico (o limite físico correto
    # longe da fonte é enriquecimento->1, já que o streaming não tem
    # mais nada para advectar). Somar o mesmo piso a ambos os lados força
    # esse limite correto sem mascarar a razão real perto da fonte, onde
    # ambas as concentrações são muito maiores que o piso.
    floor = np.max(c_control) * 1e-6 + 1e-30
    enrichment = np.clip((c_stream + floor) / (c_control + floor), 1e-6, None)
    speed_max = float(np.max(np.sqrt(ux**2 + uy**2)))
    return enrichment, speed_max


# --------------------------------------------------------------------------
# 7. Orquestrador de alto nível
# --------------------------------------------------------------------------

def sample_field_at_vents(field_grid: np.ndarray, vents: List["Vent"]) -> Dict[int, float]:
    """Amostra o campo (índices de grade = posição x,y da fumarola) por vizinho mais próximo."""
    size = field_grid.shape[0]
    out = {}
    for v in vents:
        xi = int(np.clip(round(v.x), 0, size - 1))
        yi = int(np.clip(round(v.y), 0, size - 1))
        out[v.id] = float(field_grid[yi, xi])
    return out


def find_field_peaks(field_grid: np.ndarray, X: np.ndarray, Y: np.ndarray, top_n: int = 10,
                      neighborhood_cells: int = 5) -> List[dict]:
    """Detecta máximos locais do campo (filtro de máximo local) e devolve os `top_n` mais altos, em metros."""
    local_max = maximum_filter(field_grid, size=neighborhood_cells) == field_grid
    ys, xs = np.where(local_max)
    values = field_grid[ys, xs]
    order = np.argsort(values)[::-1][:top_n]
    return [
        {"x_m": float(X[ys[i], xs[i]]), "y_m": float(Y[ys[i], xs[i]]), "enrichment": float(values[i])}
        for i in order
    ]


def acoustic_enrichment_field(vents: List["Vent"], terrain: np.ndarray, domain_size_m: float,
                               local_relief_m: float, ocean_depth_baseline_m: float,
                               mode: str, rng: np.random.Generator,
                               ambient_temp_c: float = AMBIENT_TEMP_C_DEFAULT,
                               salinity_psu: float = 34.7, ph: float = 7.8,
                               particle_radius_m: Optional[float] = None,
                               particle_density_kg_m3: Optional[float] = None,
                               aggregate_radius_m: Optional[float] = None,
                               aggregate_density_kg_m3: Optional[float] = None,
                               cross_vent_coherence: str = "incoherent",
                               ) -> dict:
    """
    Ponto de entrada único do módulo acústico. `mode` em
    {"streaming","particle_trap","both"} ("off" nunca deve chegar aqui —
    filtrado pelo chamador). Retorna um dict com o campo final de
    enriquecimento (para visualização/detecção de picos), o fator por
    fumarola (para os módulos de prebiotic.py) e diagnósticos honestos
    sobre a plausibilidade física de cada mecanismo nas condições
    simuladas.

    `cross_vent_coherence` ("incoherent" padrão | "coherent"): ver
    docstring do módulo e de `compute_acoustic_field` — "coherent" é um
    limite superior idealizado (todas as fumarolas em uma única
    frequência compartilhada, somadas em fase), usado para testar se a
    suposição de incoerência entre fumarolas (a escolha fisicamente
    motivada, mas não medida diretamente) afeta a conclusão do modelo.

    `particle_radius_m`/`particle_density_kg_m3`: se AMBOS omitidos
    (padrão), o modo particle_trap/both usa a POPULAÇÃO de duas classes
    ancoradas em literatura (`PARTICLE_CLASSES` — colóide fino vs.
    agregado de campo próximo, ver docs/PHYSICS_MODEL.md), reportando
    diagnósticos para as duas e usando a classe mais favorável
    (`PRIMARY_PARTICLE_CLASS`) como campo principal. Se fornecidos
    explicitamente, usa esse ÚNICO tamanho customizado em vez da
    população citada (modo de exploração, ex.: "que tamanho seria
    necessário para a armadilha ficar relevante?").

    `aggregate_radius_m`/`aggregate_density_kg_m3`: só têm efeito
    quando a população citada está ativa (parâmetros acima omitidos) —
    sobrescrevem APENAS a classe `PRIMARY_PARTICLE_CLASS` (agregado),
    mantendo o colóide fino fixo. Usado pela varredura de sensibilidade
    (`--sensitivity-sweep` em fumarola_field.py) para amostrar dentro da
    faixa documentada 14-20 μm / 2400-3600 kg/m³ (González-Santana et
    al., 2020) em vez de fixar no ponto médio.
    """
    if mode not in ("streaming", "particle_trap", "both"):
        raise ValueError(f"modo acústico inválido: {mode!r}")

    field = compute_acoustic_field(vents, terrain, domain_size_m, local_relief_m,
                                    ocean_depth_baseline_m, ambient_temp_c, salinity_psu, ph, rng,
                                    cross_vent_coherence=cross_vent_coherence)

    diagnostics = {
        "sound_speed_m_s": field.sound_speed_m_s,
        "absorption_np_per_m_at_100hz": field.absorption_np_per_m_at_100hz,
        "cross_vent_coherence": cross_vent_coherence,
    }

    enrichment_streaming = enrichment_particle = None
    speed_max = depth_over_kt = None

    if mode in ("streaming", "both"):
        enrichment_streaming, speed_max = streaming_enrichment_field(field, vents, domain_size_m)
        diagnostics["streaming_speed_max_m_s"] = speed_max

    if mode in ("particle_trap", "both"):
        if particle_radius_m is not None and particle_density_kg_m3 is not None:
            u_field = gorkov_potential_field(field, particle_radius_m, particle_density_kg_m3)
            enrichment_particle, depth_over_kt = particle_boltzmann_enhancement(u_field, ambient_temp_c)
            diagnostics["gorkov_trap_depth_over_kT"] = depth_over_kt
            diagnostics["gorkov_trap_physically_relevant"] = bool(depth_over_kt is not None and depth_over_kt > 1.0)
            diagnostics["particle_classes"] = None
        else:
            class_results = {}
            for key, spec in PARTICLE_CLASSES.items():
                r = spec["radius_m"]
                rho = spec["density_kg_m3"]
                if key == PRIMARY_PARTICLE_CLASS:
                    r = aggregate_radius_m if aggregate_radius_m is not None else r
                    rho = aggregate_density_kg_m3 if aggregate_density_kg_m3 is not None else rho
                u_field_c = gorkov_potential_field(field, r, rho)
                enrich_c, depth_c = particle_boltzmann_enhancement(u_field_c, ambient_temp_c)
                class_results[key] = {
                    "radius_um": r * 1e6,
                    "density_kg_m3": rho,
                    "trap_depth_over_kT": depth_c,
                    "physically_relevant": bool(depth_c > 1.0),
                    "_field": enrich_c,
                }
            diagnostics["particle_classes"] = {
                k: {kk: vv for kk, vv in v.items() if kk != "_field"} for k, v in class_results.items()
            }
            primary = class_results[PRIMARY_PARTICLE_CLASS]
            enrichment_particle = primary["_field"]
            depth_over_kt = primary["trap_depth_over_kT"]
            diagnostics["gorkov_trap_depth_over_kT"] = depth_over_kt
            diagnostics["gorkov_trap_physically_relevant"] = primary["physically_relevant"]

    if mode == "streaming":
        combined = enrichment_streaming
    elif mode == "particle_trap":
        combined = enrichment_particle
    else:
        combined = enrichment_streaming * enrichment_particle

    per_vent_factor = sample_field_at_vents(combined, vents)
    peaks = find_field_peaks(combined, field.X, field.Y, top_n=10)

    return {
        "mode": mode,
        "X_m": field.X,
        "Y_m": field.Y,
        "enrichment_field": combined,
        "per_vent_factor": per_vent_factor,
        "peaks": peaks,
        "diagnostics": diagnostics,
    }
